/**
 * Generates Zustand store from a CodegenModel.
 * Follows adh-web pattern: create<T>()((set, get) => ({...}))
 */

import type { CodegenModel } from './codegen-model.js';

export const generateStore = (model: CodegenModel): string => {
  const lines: string[] = [];
  const { domain, domainPascal } = model;

  lines.push(`// Store for ${domainPascal} (IDE ${model.programId})`);
  lines.push(`// Auto-generated by Migration Factory v8 - edit after generation`);
  lines.push('');
  lines.push(`import { create } from 'zustand';`);
  lines.push(`import type { ${domainPascal}State } from '@/types/${domain}';`);

  // Import API if we have calls
  if (model.apiCalls.length > 0) {
    lines.push(`import { ${domain}Api } from '@/services/api/${domain}Api';`);
  }

  lines.push('');

  // Store interface
  lines.push(`interface ${domainPascal}Store extends ${domainPascal}State {`);
  for (const action of model.actions) {
    lines.push(`  ${action.handlerName}: () => Promise<void>; // ${action.id}`);
  }
  if (model.apiCalls.length > 0) {
    lines.push('  fetchData: () => Promise<void>;');
  }
  lines.push('  reset: () => void;');
  lines.push('}');
  lines.push('');

  // Initial state
  lines.push(`const initialState: ${domainPascal}State = {`);
  lines.push('  isLoading: false,');
  lines.push('  error: null,');
  for (const field of model.stateFields) {
    const defaultVal = field.source === 'prop' ? "''" : 'null';
    lines.push(`  ${field.name}: ${defaultVal},`);
  }
  for (const entity of model.entities) {
    lines.push(`  ${entity.name}List: [],`);
  }
  lines.push('};');
  lines.push('');

  // Store creation
  lines.push(`export const use${domainPascal}Store = create<${domainPascal}Store>()((set, get) => ({`);
  lines.push('  ...initialState,');
  lines.push('');

  // Actions from rules
  for (const action of model.actions) {
    lines.push(`  // TODO: ${action.id} - ${action.description}`);
    if (action.condition) {
      lines.push(`  // Condition: ${action.condition}`);
    }
    lines.push(`  ${action.handlerName}: async () => {`);
    lines.push(`    set({ isLoading: true, error: null });`);
    lines.push(`    try {`);
    lines.push(`      // TODO: implement ${action.id}`);
    lines.push(`    } catch (err) {`);
    lines.push(`      set({ error: String(err) });`);
    lines.push(`    } finally {`);
    lines.push(`      set({ isLoading: false });`);
    lines.push(`    }`);
    lines.push(`  },`);
    lines.push('');
  }

  // Fetch data action
  if (model.apiCalls.length > 0) {
    lines.push('  fetchData: async () => {');
    lines.push('    set({ isLoading: true, error: null });');
    lines.push('    try {');
    for (const call of model.apiCalls) {
      if (call.method === 'GET') {
        lines.push(`      // TODO: ${call.calleeName}`);
        lines.push(`      // const data = await ${domain}Api.${call.name}();`);
      }
    }
    lines.push('    } catch (err) {');
    lines.push('      set({ error: String(err) });');
    lines.push('    } finally {');
    lines.push('      set({ isLoading: false });');
    lines.push('    }');
    lines.push('  },');
    lines.push('');
  }

  lines.push('  reset: () => set(initialState),');
  lines.push('}));');
  lines.push('');

  return lines.join('\n');
};
