/**
 * Generates Vitest test file for the Zustand store from a CodegenModel.
 * Follows Vitest pattern: beforeEach reset, initial state test, one stub per action.
 */

import type { CodegenModel } from './codegen-model.js';

export const generateTests = (model: CodegenModel): string => {
  const lines: string[] = [];
  const { domain, domainPascal } = model;

  lines.push(`// Tests for ${domainPascal}Store (IDE ${model.programId})`);
  lines.push(`// Auto-generated by Migration Factory v8 - edit after generation`);
  lines.push('');
  lines.push(`import { describe, it, expect, beforeEach } from 'vitest';`);
  lines.push(`import { use${domainPascal}Store } from '@/stores/${domain}Store';`);
  lines.push('');

  lines.push(`describe('${domainPascal}Store', () => {`);
  lines.push('  beforeEach(() => {');
  lines.push(`    use${domainPascal}Store.setState({`);
  lines.push('      isLoading: false,');
  lines.push('      error: null,');
  for (const field of model.stateFields) {
    const defaultVal = field.source === 'prop' ? "''" : 'null';
    lines.push(`      ${field.name}: ${defaultVal},`);
  }
  for (const entity of model.entities) {
    lines.push(`      ${entity.name}List: [],`);
  }
  lines.push('    });');
  lines.push('  });');
  lines.push('');

  // Initial state test
  lines.push("  it('should have correct initial state', () => {");
  lines.push(`    const state = use${domainPascal}Store.getState();`);
  lines.push('    expect(state.isLoading).toBe(false);');
  lines.push('    expect(state.error).toBeNull();');
  for (const entity of model.entities) {
    lines.push(`    expect(state.${entity.name}List).toEqual([]);`);
  }
  lines.push('  });');
  lines.push('');

  // One test per action
  for (const action of model.actions) {
    lines.push(`  // TODO: ${action.id} - ${action.description}`);
    lines.push(`  it('should handle ${action.handlerName}', async () => {`);
    lines.push(`    const { ${action.handlerName} } = use${domainPascal}Store.getState();`);
    lines.push(`    await ${action.handlerName}();`);
    lines.push(`    const state = use${domainPascal}Store.getState();`);
    lines.push('    expect(state.isLoading).toBe(false);');
    lines.push(`    // TODO: add specific assertions for ${action.id}`);
    lines.push('  });');
    lines.push('');
  }

  // Reset test
  lines.push("  it('should reset state', () => {");
  lines.push(`    use${domainPascal}Store.setState({ isLoading: true, error: 'test' });`);
  lines.push(`    use${domainPascal}Store.getState().reset();`);
  lines.push(`    const state = use${domainPascal}Store.getState();`);
  lines.push('    expect(state.isLoading).toBe(false);');
  lines.push('    expect(state.error).toBeNull();');
  lines.push('  });');

  lines.push('});');
  lines.push('');

  return lines.join('\n');
};
