/**
 * Prisma Schema Generator
 * Generate schema.prisma from tables + relations
 */

import type { Table, Relation } from './types.js';

export const generatePrismaSchema = (tables: Table[], relations: Relation[]): string => {
  const models = tables.map(t => generateModel(t, relations)).join('\n\n');
  
  return `// Generated by @magic-migration/data-model
// Date: ${new Date().toISOString()}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

${models}
`;
};

const generateModel = (table: Table, relations: Relation[]): string => {
  const fields = table.columns.map(c => {
    const type = mapType(c.type);
    const modifiers = [];
    if (c.isPrimaryKey) modifiers.push('@id');
    if (!c.nullable) modifiers.push('');
    return `  ${c.name} ${type}${c.nullable ? '?' : ''} ${modifiers.join(' ')}`;
  }).join('\n');

  const tableRelations = relations.filter(r => r.fromTable === table.id);
  const relationFields = tableRelations.map(r => {
    const targetTable = 'RelatedTable';
    return `  ${targetTable.toLowerCase()} ${targetTable}? @relation(fields: [${table.columns[0].name}], references: [id])`;
  }).join('\n');

  return `model ${table.name} {
${fields}
${relationFields ? relationFields : ''}
}`;
};

const mapType = (magicType: string): string => {
  const typeMap: Record<string, string> = {
    'ALPHA': 'String',
    'NUMERIC': 'Int',
    'DATE': 'DateTime',
    'LOGICAL': 'Boolean',
    'unknown': 'String',
  };
  return typeMap[magicType] || 'String';
};
